### ISSUE TITLE
Segmentation fault with LLVM 4.0

### ISSUE THREAD

**Issue by ajor** [ajor/bpftrace#4]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000100e56c74 in llvm::RuntimeDyldELF::resolveRelocation(llvm::RelocationEntry const&, unsigned long) ()
(gdb) bt
#0  0x0000000100e56c74 in llvm::RuntimeDyldELF::resolveRelocation(llvm::RelocationEntry const&, unsigned long) ()
#1  0x0000000100e56ca5 in llvm::RuntimeDyldELF::resolveRelocation(llvm::RelocationEntry const&, unsigned long) ()
#2  0x0000000100e56ca5 in llvm::RuntimeDyldELF::resolveRelocation(llvm::RelocationEntry const&, unsigned long) ()
#3  0x0000000100e3eba9 in llvm::RuntimeDyldImpl::resolveRelocationList(llvm::SmallVector<llvm::RelocationEntry, 64u> const&, unsigned long) ()
#4  0x0000000100e41e89 in llvm::RuntimeDyldImpl::resolveRelocations() ()
#5  0x00000001003d35e1 in llvm::MCJIT::finalizeLoadedModules() ()
#6  0x00000001003d3bc2 in llvm::MCJIT::finalizeObject() ()
#7  0x00000001002f36fe in bpftrace::ast::CodegenLLVM::compile (this=0x7fffffffe4f0, debug=true) at /home/alastair/src/bpftrace/src/codegen_llvm.cpp:555
#8  0x0000000100306728 in main (argc=4, argv=0x7fffffffe878) at /home/alastair/src/bpftrace/src/main.cpp:86
```

**Comment by ajor** [comment]
BPFtrace now uses LLVM 5
